// import React from "react";
// import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from "@/components/ui/table";
// import styles from '../footerpage.module.css'
// import InnerBanner from "@/components/InnerBanner/InnerBanner";



// const CommissionDisclosurePage = () => {
//     return (
//         <div className={`${styles.footerpage} `}>
//             <InnerBanner pageName={"Commission Disclosure"} />
//             <div className="max-w-screen-xl mx-auto main-section">

//                 <h2 className="text-xl  font-bold text-[var(--primary)] mb-2 mt-2">Commission Disclosure under SEBI Circular SEBI/IMD/CIR No.4 /168230/09</h2>
//                 <p className="text-md  mb-4">The details of the commission earned by us from various Asset Management Companies (AMCs) are as below:</p>
//                 <Table className="border border-gray-300 w-full text-lg">
//                     <TableHeader>
//                         <TableRow className="bg-[var(--rv-secondary)] text-[var(--rv-white)]">
//                             <TableHead className="px-4 py-3">Scheme Type</TableHead>
//                             <TableHead className="px-4 py-3">Trail 1st Year</TableHead>
//                             <TableHead className="px-4 py-3">Trail 2nd Year Onwards</TableHead>
//                         </TableRow>
//                     </TableHeader>
//                     <TableBody>
//                         {commissionData.map((item, index) => (
//                             <TableRow key={index} className="border-b">
//                                 <TableCell className="px-4 py-3 font-semibold text-[var(--rv-white)] bg-[var(--primary)]">{item.scheme}</TableCell>
//                                 <TableCell className="px-4 py-3 text-[var(--rv-white)] bg-[var(--primary)]">{item.trail1}</TableCell>
//                                 <TableCell className="px-4 py-3 text-[var(--rv-white)] bg-[var(--primary)]">{item.trail2}</TableCell>
//                             </TableRow>
//                         ))}
//                     </TableBody>
//                 </Table>

//                 <p className="text-md  my-6 text-justify">*Investments in mutual funds are subject to market risk and customers should read the scheme-related documents / key information documents of the Mutual Fund products carefully before investing. This is on a best-effort basis and rates are updated as and when actual rates are received from AMCs. This is for information purposes only and does not represent any financial or other advice. The information contained in this presentation is general in nature. The client acknowledges that the prices and net asset values of the mutual fund schemes are subject to fluctuation based on the factors and the forces affecting the capital markets. Past performance of the sponsors, mutual funds, or their affiliates do not indicate or guarantee the future performance of any scheme in any manner, and historical performance, when presented, is purely for reference purposes. This page is an integral part of the document generated by us. Investment proposals are prepared on request of the client for general information and reference purposes. It aims to demonstrate a proposal considering the client’s investment objective and investment preferences designed based on information provided by the client. The proposal is purely on a non-binding basis and the client is free to accept or reject the proposal. We shall not be held responsible for any direct or indirect loss caused by relying on this information. The client is free to seek the opinion of the legal, investment, and taxation advisor for making investment decisions. </p>
//             </div>

//         </div>
//     );
// };

// // Sample data for table
// const commissionData = [
//     { scheme: "Arbitrage Funds", trail1: "0.05% to 0.60%", trail2: "0.05% to 0.60%" },
//     { scheme: "ELSS Funds", trail1: "0.50% to 1.25%", trail2: "0.50% to 1.25%" },
//     { scheme: "Equity Oriented Funds", trail1: "0.50% to 1.25%", trail2: "0.50% to 1.25%" },
//     { scheme: "Aggressive Hybrid Equity Funds", trail1: "0.50% to 1.25%", trail2: "0.50% to 1.25%" },
//     { scheme: "Fixed Maturity Plans", trail1: "0.05% to 0.50%", trail2: "0.05% to 0.50%" },
//     { scheme: "Fund of Funds", trail1: "0.25% to 1%", trail2: "0.25% to 1%" },
//     { scheme: "Gilt Funds", trail1: "0.25% to 1%", trail2: "0.05% to 0.65%" },
//     { scheme: "Hybrid Debt Funds", trail1: "0.05% to 0.75%", trail2: "0.05% to 0.75%" },
//     { scheme: "Income Funds", trail1: "0.05% to 1%", trail2: "0.05% to 1%" },
//     { scheme: "Index Funds", trail1: "0.01% to 0.75%", trail2: "0.01% to 0.75%" },
//     { scheme: "Liquid Funds / Ultra Short-Term Funds", trail1: "0.05% to 0.50%", trail2: "0.05% to 0.50%" },
//     { scheme: "Short-Term Income Funds", trail1: "0.05% to 0.65%", trail2: "0.05% to 0.65%" },
//     { scheme: "Thematic / Sector Funds", trail1: "0.50% to 1.25%", trail2: "0.50% to 1.25%" },
// ];

// export default CommissionDisclosurePage;